### ISSUE TITLE
social-icons-simple not loading all the icons for single author page

### ISSUE THREAD

**Issue by yayitazale** [themefisher/bookworm-light-astro#9]
Hi:

I added this in a author page:

```
---
title: author1
image: /images/authors/photo.jpg
description: author1 description.
social:
  gitlab: https://gitlab.com/author1
  linkedin: https://www.linkedin.com/in/author1
  instagram: https://www.instagram.com/author1
  twitter: https://twitter.com/author
  website: https:/author1.me/
---
```

But it only render Instagram and Twitter:

![imagen](https://github.com/themefisher/bookworm-light-astro/assets/6462849/0bb57f2e-904b-4e5c-8614-14b02307b071)

However, in the footer, it does render all the socials filled in social.json:

![imagen](https://github.com/themefisher/bookworm-light-astro/assets/6462849/c7b9f4a5-110c-4c3f-86d0-66e35838b30d)
